name: Release
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: bazelbuild/setup-bazelisk@v2.0.0
    - run: bazel build //...
    - uses: actions/upload-artifact@v3.1.3
      with:
        path: bazel-bin/src/hello
        name: hello
        if-no-files-found: error
        retention-days: 1

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: hello
      - uses: softprops/action-gh-release@v1
        with:
          files: hello
