name: Release
on:
  workflow_dispatch:
  release: types: [created]

jobs:
  build:
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: bazelbuild/setup-bazelisk@v2.0.0
    - run: bazel build //... && mv bazel-bin/src/hello .
